filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Evening Alfredo, Welcome to Coot version 0.8.9.2")
use_graphics_interface_state ()
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good evening Alfredo. Welcome to Coot 0.8.9.2")
set_display_lists_for_maps (0)
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
set_find_hydrogen_torsion (1)
use_graphics_interface_state ()
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine.pdb", 1)
set_molecule_bonds_colour_map_rotation (0, 140.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (1)
close_molecule (2)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (3)
close_molecule (4)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (5)
close_molecule (6)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (7)
close_molecule (8)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (9)
close_molecule (10)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (11)
close_molecule (12)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (13)
close_molecule (14)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (15)
close_molecule (16)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (17)
close_molecule (18)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (19)
close_molecule (20)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (21)
close_molecule (22)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (23)
close_molecule (24)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (25)
close_molecule (26)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (27)
close_molecule (28)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (0)
close_molecule (29)
close_molecule (30)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/DS3_refine_2.pdb", 1)
set_molecule_bonds_colour_map_rotation (31, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/DS3_refine_2.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_2/DS3_refine_2.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (32)
close_molecule (33)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine.pdb", 1)
set_molecule_bonds_colour_map_rotation (34, 140.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (35)
close_molecule (36)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (37)
close_molecule (38)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (39)
close_molecule (40)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (41)
close_molecule (42)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (43)
close_molecule (44)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (45)
close_molecule (46)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (47)
close_molecule (48)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (49)
close_molecule (50)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (51)
close_molecule (52)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (53)
close_molecule (54)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (55)
close_molecule (56)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (57)
close_molecule (58)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (59)
close_molecule (60)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (61)
close_molecule (62)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (34)
close_molecule (63)
close_molecule (64)
close_molecule (31)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/DS3_refine_3.pdb", 1)
set_molecule_bonds_colour_map_rotation (65, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/DS3_refine_3.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_3/DS3_refine_3.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (66)
close_molecule (67)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine.pdb", 1)
set_molecule_bonds_colour_map_rotation (68, 140.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (69)
close_molecule (70)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (71)
close_molecule (72)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (73)
close_molecule (74)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (75)
close_molecule (76)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (77)
close_molecule (78)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (79)
close_molecule (80)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (81)
close_molecule (82)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (83)
close_molecule (84)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (85)
close_molecule (86)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (68)
close_molecule (87)
close_molecule (88)
close_molecule (65)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/DS3_refine_4.pdb", 1)
set_molecule_bonds_colour_map_rotation (89, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/DS3_refine_4.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-gmp-DS3/phenixDS3/Refine_4/DS3_refine_4.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
