(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Evening Alfredo, Welcome to Coot version 0.8.9.2")
(use-graphics-interface-state)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good evening Alfredo. Welcome to Coot 0.8.9.2")
(set-display-lists-for-maps 0)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(set-find-hydrogen-torsion 1)
(use-graphics-interface-state)
