(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Evening Alfredo, Welcome to Coot version 0.8.9.2")
(use-graphics-interface-state)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good evening Alfredo. Welcome to Coot 0.8.9.2")
(set-display-lists-for-maps 0)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(set-find-hydrogen-torsion 1)
(use-graphics-interface-state)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_5/apo-ds1_refine_5.pdb" 1)
(set-molecule-bonds-colour-map-rotation 0 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_5/apo-ds1_refine_5.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_5/apo-ds1_refine_5.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(command-in-path-or-absolute? *probe-command*)
(graphics-molecule-bond-type 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-delete-residue-mode)
(delete-residue 0 "A" 6 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 0 27 1)
(set-delete-residue-mode)
(delete-residue 0 "A" 3 "")
(delete-residue-by-atom-index 0 5 1)
(delete-residue 0 "A" 4 "")
(delete-residue-by-atom-index 0 1 1)
(delete-residue 0 "A" 5 "")
(delete-residue-by-atom-index 0 1 1)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(clear-pending-delete-item)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-delete-residue-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "A" 11 )
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(apply-undo)
(apply-undo)
(apply-undo)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(delete-residue-sidechain 0 "A" 76 )
(set-delete-residue-mode)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 0 "A" 77 "")
(delete-residue-by-atom-index 0 560 1)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 0 "A" 78 "")
(delete-residue-by-atom-index 0 561 1)
(delete-residue 0 "A" 80 "")
(delete-residue-by-atom-index 0 569 1)
(delete-residue 0 "A" 79 "")
(delete-residue-by-atom-index 0 560 1)
(set-delete-residue-mode)
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 0 "A" 83 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 0 582 1)
(set-delete-residue-mode)
(delete-residue 0 "A" 81 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 0 565 1)
(set-delete-residue-mode)
(delete-residue 0 "A" 82 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 0 560 1)
(set-delete-residue-mode)
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 0 "A" 92 "")
(delete-residue-by-atom-index 0 624 1)
(delete-residue 0 "A" 91 "")
(delete-residue-by-atom-index 0 619 1)
(delete-residue 0 "A" 90 "")
(delete-residue-by-atom-index 0 612 1)
(delete-residue 0 "A" 88 "")
(delete-residue-by-atom-index 0 593 1)
(delete-residue 0 "A" 65 "")
(delete-residue-by-atom-index 0 468 1)
(set-delete-residue-mode)
(delete-residue 0 "A" 89 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 0 590 1)
(clear-pending-delete-item)
(clear-pending-delete-item)
(graphics-general-key-press-hook 65406)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-delete-residue-mode)
(delete-residue 0 "B" 3 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 0 1249 1)
(set-delete-residue-mode)
(delete-residue 0 "B" 4 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 0 1243 1)
(set-delete-residue-mode)
(set-delete-atom-mode)
(delete-atom 0 "B" 41 "" " NH2" "")
(delete-atom 0 "B" 41 "" " CZ " "")
(delete-atom 0 "B" 41 "" " NE " "")
(delete-atom 0 "B" 41 "" " CD " "")
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-atom-mode)
(delete-atom 0 "B" 41 "" " NH1" "")
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-sidechain-mode)
(first-coords-imol)
(first-unsaved-coords-imol)
(filter-fileselection-filenames-state)
