filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Alfredo, Welcome to Coot version 0.8.9.2")
use_graphics_interface_state ()
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good afternoon Alfredo. Welcome to Coot 0.8.9.2")
set_display_lists_for_maps (0)
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
set_find_hydrogen_torsion (1)
use_graphics_interface_state ()
