(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Alfredo, Welcome to Coot version 0.8.9.2")
(use-graphics-interface-state)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon Alfredo. Welcome to Coot 0.8.9.2")
(set-display-lists-for-maps 0)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(set-find-hydrogen-torsion 1)
(use-graphics-interface-state)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine.pdb" 1)
(set-molecule-bonds-colour-map-rotation 0 140.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 1)
(close-molecule 2)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 3)
(close-molecule 4)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 5)
(close-molecule 6)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 7)
(close-molecule 8)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 9)
(close-molecule 10)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 11)
(close-molecule 12)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 13)
(close-molecule 14)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 15)
(close-molecule 16)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 0)
(close-molecule 17)
(close-molecule 18)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/apo-ds1_refine_7.pdb" 1)
(set-molecule-bonds-colour-map-rotation 19 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/apo-ds1_refine_7.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/apo-ds1_refine_7.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(set-go-to-atom-molecule 19)
(command-in-path-or-absolute? *probe-command*)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-delete-residue-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 19 "A" 29 )
(set-go-to-atom-molecule 19)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 19 "A" 32 )
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 19 "A" 41 )
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(apply-undo)
(set-go-to-atom-molecule 19)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 19 "A" 42 )
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 19 "A" 52 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 19 "A" 56 )
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "GLY" 0)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(set-delete-residue-mode)
(delete-residue 19 "A" 72 "")
(delete-residue-by-atom-index 19 489 1)
(delete-residue 19 "A" 71 "")
(delete-residue-by-atom-index 19 476 1)
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 19 "A" 84 "")
(delete-residue-by-atom-index 19 511 1)
(delete-residue 19 "A" 85 "")
(delete-residue-by-atom-index 19 508 1)
(delete-residue 19 "A" 86 "")
(delete-residue-by-atom-index 19 508 1)
(delete-residue 19 "A" 87 "")
(delete-residue-by-atom-index 19 513 1)
(clear-pending-delete-item)
(clear-pending-delete-item)
(apply-undo)
(apply-undo)
(apply-undo)
(apply-undo)
(apply-undo)
(apply-undo)
(apply-redo)
(apply-redo)
(apply-redo)
(apply-redo)
(apply-redo)
(apply-redo)
(apply-redo)
(apply-redo)
(apply-redo)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "VAL" 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "GLY" 0)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "ILE" 0)
(set-delete-residue-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 19 "B" 15 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(set-delete-residue-mode)
(delete-residue 19 "B" 32 "")
(delete-residue-by-atom-index 19 1389 1)
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 19 "B" 31 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 1381 1)
(set-go-to-atom-molecule 19)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "ILE" 0)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(apply-undo)
(setup-mutate-auto-fit 0)
(set-go-to-atom-molecule 19)
(set-delete-residue-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 19 "B" 29 )
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(apply-undo)
(apply-undo)
(set-go-to-atom-molecule 19)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 19 "B" 52 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 19 "B" 61 )
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "ARG" 0)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(set-delete-residue-mode)
(delete-residue 19 "B" 74 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 1712 1)
(set-delete-residue-mode)
(delete-residue 19 "B" 78 "")
(delete-residue-by-atom-index 19 1732 1)
(delete-residue 19 "B" 79 "")
(delete-residue-by-atom-index 19 1733 1)
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 19 "B" 83 "")
(delete-residue-by-atom-index 19 1757 1)
(delete-residue 19 "B" 84 "")
(delete-residue-by-atom-index 19 1758 1)
(delete-residue 19 "B" 85 "")
(delete-residue-by-atom-index 19 1758 1)
(delete-residue 19 "B" 86 "")
(delete-residue-by-atom-index 19 1758 1)
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 19 "B" 87 "")
(delete-residue-by-atom-index 19 1758 1)
(delete-residue 19 "B" 88 "")
(delete-residue-by-atom-index 19 1758 1)
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 19 "B" 81 "")
(delete-residue-by-atom-index 19 1741 1)
(delete-residue 19 "B" 82 "")
(delete-residue-by-atom-index 19 1740 1)
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-delete-residue-mode)
(delete-residue 19 "B" 89 "")
(delete-residue-by-atom-index 19 1741 1)
(delete-residue 19 "B" 90 "")
(delete-residue-by-atom-index 19 1740 1)
(clear-pending-delete-item)
(clear-pending-delete-item)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(set-delete-residue-mode)
(delete-residue 19 "B" 80 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 1732 1)
(set-delete-residue-mode)
(delete-residue 19 "C" 4 "")
(delete-residue-by-atom-index 19 2416 1)
(delete-residue 19 "C" 3 "")
(delete-residue-by-atom-index 19 2399 1)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 19 "C" 73 "")
(delete-residue-by-atom-index 19 2945 1)
(delete-residue 19 "C" 75 "")
(delete-residue-by-atom-index 19 2951 1)
(delete-residue 19 "C" 76 "")
(delete-residue-by-atom-index 19 2952 1)
(delete-residue 19 "C" 74 "")
(delete-residue-by-atom-index 19 2945 1)
(delete-residue 19 "C" 77 "")
(delete-residue-by-atom-index 19 2945 1)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 19 "C" 79 "")
(delete-residue-by-atom-index 19 2951 1)
(delete-residue 19 "C" 80 "")
(delete-residue-by-atom-index 19 2951 1)
(delete-residue 19 "C" 81 "")
(delete-residue-by-atom-index 19 2951 1)
(delete-residue 19 "C" 82 "")
(delete-residue-by-atom-index 19 2951 1)
(delete-residue 19 "C" 83 "")
(delete-residue-by-atom-index 19 2952 1)
(delete-residue 19 "C" 84 "")
(delete-residue-by-atom-index 19 2951 1)
(delete-residue 19 "C" 78 "")
(delete-residue-by-atom-index 19 2945 1)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 19 "C" 85 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 2944 1)
(set-delete-residue-mode)
(delete-residue 19 "C" 86 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 2945 1)
(set-delete-residue-mode)
(delete-residue 19 "C" 87 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 2944 1)
(first-coords-imol)
(first-unsaved-coords-imol)
(filter-fileselection-filenames-state)
(set-delete-residue-mode)
(delete-residue 19 "C" 72 "")
(delete-residue-by-atom-index 19 2936 1)
(delete-residue 19 "C" 71 "")
(delete-residue-by-atom-index 19 2924 1)
(delete-residue 19 "C" 70 "")
(delete-residue-by-atom-index 19 2917 1)
(clear-pending-delete-item)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(set-go-to-atom-molecule 19)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "THR" 0)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "LEU" 0)
(set-delete-residue-mode)
(delete-residue 19 "C" 91 "")
(delete-residue-by-atom-index 19 2960 1)
(delete-residue 19 "C" 90 "")
(delete-residue-by-atom-index 19 2951 1)
(delete-residue 19 "C" 89 "")
(delete-residue-by-atom-index 19 2943 1)
(delete-residue 19 "C" 88 "")
(delete-residue-by-atom-index 19 2932 1)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 19 "C" 92 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 2932 1)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "GLY" 0)
(set-delete-residue-mode)
(delete-residue 19 "D" 3 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 3596 1)
(apply-undo)
(set-delete-residue-mode)
(delete-residue 19 "D" 3 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 3596 1)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "TYR" 0)
(apply-undo)
(set-delete-residue-mode)
(delete-residue 19 "D" 55 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 4014 1)
(set-delete-residue-mode)
(delete-residue 19 "D" 71 "")
(delete-residue-by-atom-index 19 4124 1)
(delete-residue 19 "D" 72 "")
(delete-residue-by-atom-index 19 4124 1)
(delete-residue 19 "D" 73 "")
(delete-residue-by-atom-index 19 4124 1)
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 19 "D" 74 "")
(delete-residue-by-atom-index 19 4125 1)
(delete-residue 19 "D" 75 "")
(delete-residue-by-atom-index 19 4124 1)
(delete-residue 19 "D" 76 "")
(delete-residue-by-atom-index 19 4125 1)
(delete-residue 19 "D" 77 "")
(delete-residue-by-atom-index 19 4124 1)
(delete-residue 19 "D" 78 "")
(delete-residue-by-atom-index 19 4124 1)
(delete-residue 19 "D" 79 "")
(delete-residue-by-atom-index 19 4124 1)
(delete-residue 19 "D" 80 "")
(delete-residue-by-atom-index 19 4124 1)
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-delete-residue-mode)
(delete-residue 19 "D" 81 "")
(delete-residue-by-atom-index 19 4124 1)
(delete-residue 19 "D" 82 "")
(delete-residue-by-atom-index 19 4124 1)
(delete-residue 19 "D" 83 "")
(delete-residue-by-atom-index 19 4123 1)
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-delete-residue-mode)
(delete-residue 19 "D" 87 "")
(delete-residue-by-atom-index 19 4148 1)
(delete-residue 19 "D" 88 "")
(delete-residue-by-atom-index 19 4148 1)
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-delete-residue-mode)
(delete-residue 19 "D" 85 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 4132 1)
(set-delete-residue-mode)
(delete-residue 19 "D" 86 "")
(delete-residue-by-atom-index 19 4132 1)
(delete-residue 19 "D" 84 "")
(delete-residue-by-atom-index 19 4124 1)
(delete-residue 19 "D" 68 "")
(delete-residue-by-atom-index 19 4107 1)
(delete-residue 19 "D" 69 "")
(delete-residue-by-atom-index 19 4101 1)
(apply-undo)
(apply-undo)
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-delete-residue-mode)
(delete-residue 19 "D" 89 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 4124 1)
(set-delete-residue-mode)
(delete-residue 19 "D" 90 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 4127 1)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-delete-residue-mode)
(delete-residue 19 "D" 164 "")
(delete-residue-by-atom-index 19 4682 1)
(delete-residue 19 "D" 169 "")
(delete-residue-by-atom-index 19 4715 1)
(delete-residue 19 "D" 165 "")
(delete-residue-by-atom-index 19 4684 1)
(delete-residue 19 "D" 166 "")
(delete-residue-by-atom-index 19 4681 1)
(delete-residue 19 "D" 49 "")
(delete-residue-by-atom-index 19 3961 1)
(delete-residue 19 "D" 168 "")
(delete-residue-by-atom-index 19 4677 1)
(delete-residue 19 "D" 170 "")
(delete-residue-by-atom-index 19 4677 1)
(delete-residue 19 "D" 167 "")
(delete-residue-by-atom-index 19 4673 1)
(clear-pending-delete-item)
(clear-pending-delete-item)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "VAL" 0)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "ASN" 0)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "LEU" 0)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "ASP" 0)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(apply-undo)
(apply-redo)
(apply-undo)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(apply-undo)
(apply-undo)
(set-go-to-atom-molecule 19)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "VAL" 0)
(apply-undo)
(apply-undo)
(apply-undo)
(apply-undo)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(apply-undo)
(apply-undo)
(set-delete-residue-mode)
(delete-residue 19 "D" 167 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 4680 1)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(apply-undo)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "VAL" 0)
(graphics-general-key-press-hook 65406)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "GLU" 0)
(set-go-to-atom-molecule 19)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(set-delete-residue-mode)
(delete-residue 19 "D" 165 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 19 4680 1)
(do-add-terminal-residue 1)
(do-add-terminal-residue 0)
(setup-mutate-auto-fit 1)
(setup-mutate-auto-fit 0)
(do-mutatation "GLU" 0)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(set-go-to-atom-molecule 19)
(apply-undo)
(apply-undo)
(first-coords-imol)
(first-unsaved-coords-imol)
(filter-fileselection-filenames-state)
