filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Alfredo, Welcome to Coot version 0.8.9.2")
use_graphics_interface_state ()
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good afternoon Alfredo. Welcome to Coot 0.8.9.2")
set_display_lists_for_maps (0)
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
set_find_hydrogen_torsion (1)
use_graphics_interface_state ()
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine.pdb", 1)
set_molecule_bonds_colour_map_rotation (0, 140.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (1)
close_molecule (2)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (3)
close_molecule (4)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (5)
close_molecule (6)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (7)
close_molecule (8)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (9)
close_molecule (10)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (11)
close_molecule (12)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (13)
close_molecule (14)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (15)
close_molecule (16)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (0)
close_molecule (17)
close_molecule (18)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/apo-ds1_refine_7.pdb", 1)
set_molecule_bonds_colour_map_rotation (19, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/apo-ds1_refine_7.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_7/apo-ds1_refine_7.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
set_go_to_atom_molecule (19)
;; # DIRECT SCHEME ((command-in-path-or-absolute? *probe-command*))
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_delete_residue_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (19, "A", 29, )
set_go_to_atom_molecule (19)
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (19, "A", 32, )
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (19, "A", 41, )
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
apply_undo ()
set_go_to_atom_molecule (19)
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (19, "A", 42, )
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (19, "A", 52, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (19, "A", 56, )
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("GLY", 0)
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
set_delete_residue_mode ()
delete_residue (19, "A", 72, "")
delete_residue_by_atom_index (19, 489, 1)
delete_residue (19, "A", 71, "")
delete_residue_by_atom_index (19, 476, 1)
clear_pending_delete_item ()
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (19, "A", 84, "")
delete_residue_by_atom_index (19, 511, 1)
delete_residue (19, "A", 85, "")
delete_residue_by_atom_index (19, 508, 1)
delete_residue (19, "A", 86, "")
delete_residue_by_atom_index (19, 508, 1)
delete_residue (19, "A", 87, "")
delete_residue_by_atom_index (19, 513, 1)
clear_pending_delete_item ()
clear_pending_delete_item ()
apply_undo ()
apply_undo ()
apply_undo ()
apply_undo ()
apply_undo ()
apply_undo ()
apply_redo ()
apply_redo ()
apply_redo ()
apply_redo ()
apply_redo ()
apply_redo ()
apply_redo ()
apply_redo ()
apply_redo ()
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("VAL", 0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("GLY", 0)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("ILE", 0)
set_delete_residue_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (19, "B", 15, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
set_delete_residue_mode ()
delete_residue (19, "B", 32, "")
delete_residue_by_atom_index (19, 1389, 1)
clear_pending_delete_item ()
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (19, "B", 31, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 1381, 1)
set_go_to_atom_molecule (19)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("ILE", 0)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
apply_undo ()
setup_mutate_auto_fit (0)
set_go_to_atom_molecule (19)
set_delete_residue_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (19, "B", 29, )
do_add_terminal_residue (1)
do_add_terminal_residue (0)
apply_undo ()
apply_undo ()
set_go_to_atom_molecule (19)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (19, "B", 52, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (19, "B", 61, )
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("ARG", 0)
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
set_delete_residue_mode ()
delete_residue (19, "B", 74, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 1712, 1)
set_delete_residue_mode ()
delete_residue (19, "B", 78, "")
delete_residue_by_atom_index (19, 1732, 1)
delete_residue (19, "B", 79, "")
delete_residue_by_atom_index (19, 1733, 1)
clear_pending_delete_item ()
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (19, "B", 83, "")
delete_residue_by_atom_index (19, 1757, 1)
delete_residue (19, "B", 84, "")
delete_residue_by_atom_index (19, 1758, 1)
delete_residue (19, "B", 85, "")
delete_residue_by_atom_index (19, 1758, 1)
delete_residue (19, "B", 86, "")
delete_residue_by_atom_index (19, 1758, 1)
clear_pending_delete_item ()
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (19, "B", 87, "")
delete_residue_by_atom_index (19, 1758, 1)
delete_residue (19, "B", 88, "")
delete_residue_by_atom_index (19, 1758, 1)
clear_pending_delete_item ()
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (19, "B", 81, "")
delete_residue_by_atom_index (19, 1741, 1)
delete_residue (19, "B", 82, "")
delete_residue_by_atom_index (19, 1740, 1)
clear_pending_delete_item ()
clear_pending_delete_item ()
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_delete_residue_mode ()
delete_residue (19, "B", 89, "")
delete_residue_by_atom_index (19, 1741, 1)
delete_residue (19, "B", 90, "")
delete_residue_by_atom_index (19, 1740, 1)
clear_pending_delete_item ()
clear_pending_delete_item ()
do_add_terminal_residue (1)
do_add_terminal_residue (0)
set_delete_residue_mode ()
delete_residue (19, "B", 80, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 1732, 1)
set_delete_residue_mode ()
delete_residue (19, "C", 4, "")
delete_residue_by_atom_index (19, 2416, 1)
delete_residue (19, "C", 3, "")
delete_residue_by_atom_index (19, 2399, 1)
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (19, "C", 73, "")
delete_residue_by_atom_index (19, 2945, 1)
delete_residue (19, "C", 75, "")
delete_residue_by_atom_index (19, 2951, 1)
delete_residue (19, "C", 76, "")
delete_residue_by_atom_index (19, 2952, 1)
delete_residue (19, "C", 74, "")
delete_residue_by_atom_index (19, 2945, 1)
delete_residue (19, "C", 77, "")
delete_residue_by_atom_index (19, 2945, 1)
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (19, "C", 79, "")
delete_residue_by_atom_index (19, 2951, 1)
delete_residue (19, "C", 80, "")
delete_residue_by_atom_index (19, 2951, 1)
delete_residue (19, "C", 81, "")
delete_residue_by_atom_index (19, 2951, 1)
delete_residue (19, "C", 82, "")
delete_residue_by_atom_index (19, 2951, 1)
delete_residue (19, "C", 83, "")
delete_residue_by_atom_index (19, 2952, 1)
delete_residue (19, "C", 84, "")
delete_residue_by_atom_index (19, 2951, 1)
delete_residue (19, "C", 78, "")
delete_residue_by_atom_index (19, 2945, 1)
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (19, "C", 85, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 2944, 1)
set_delete_residue_mode ()
delete_residue (19, "C", 86, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 2945, 1)
set_delete_residue_mode ()
delete_residue (19, "C", 87, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 2944, 1)
first_coords_imol ()
first_unsaved_coords_imol ()
filter_fileselection_filenames_state ()
set_delete_residue_mode ()
delete_residue (19, "C", 72, "")
delete_residue_by_atom_index (19, 2936, 1)
delete_residue (19, "C", 71, "")
delete_residue_by_atom_index (19, 2924, 1)
delete_residue (19, "C", 70, "")
delete_residue_by_atom_index (19, 2917, 1)
clear_pending_delete_item ()
do_add_terminal_residue (1)
do_add_terminal_residue (0)
set_go_to_atom_molecule (19)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("THR", 0)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("LEU", 0)
set_delete_residue_mode ()
delete_residue (19, "C", 91, "")
delete_residue_by_atom_index (19, 2960, 1)
delete_residue (19, "C", 90, "")
delete_residue_by_atom_index (19, 2951, 1)
delete_residue (19, "C", 89, "")
delete_residue_by_atom_index (19, 2943, 1)
delete_residue (19, "C", 88, "")
delete_residue_by_atom_index (19, 2932, 1)
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (19, "C", 92, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 2932, 1)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("GLY", 0)
set_delete_residue_mode ()
delete_residue (19, "D", 3, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 3596, 1)
apply_undo ()
set_delete_residue_mode ()
delete_residue (19, "D", 3, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 3596, 1)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("TYR", 0)
apply_undo ()
set_delete_residue_mode ()
delete_residue (19, "D", 55, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 4014, 1)
set_delete_residue_mode ()
delete_residue (19, "D", 71, "")
delete_residue_by_atom_index (19, 4124, 1)
delete_residue (19, "D", 72, "")
delete_residue_by_atom_index (19, 4124, 1)
delete_residue (19, "D", 73, "")
delete_residue_by_atom_index (19, 4124, 1)
clear_pending_delete_item ()
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (19, "D", 74, "")
delete_residue_by_atom_index (19, 4125, 1)
delete_residue (19, "D", 75, "")
delete_residue_by_atom_index (19, 4124, 1)
delete_residue (19, "D", 76, "")
delete_residue_by_atom_index (19, 4125, 1)
delete_residue (19, "D", 77, "")
delete_residue_by_atom_index (19, 4124, 1)
delete_residue (19, "D", 78, "")
delete_residue_by_atom_index (19, 4124, 1)
delete_residue (19, "D", 79, "")
delete_residue_by_atom_index (19, 4124, 1)
delete_residue (19, "D", 80, "")
delete_residue_by_atom_index (19, 4124, 1)
clear_pending_delete_item ()
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (19, "D", 81, "")
delete_residue_by_atom_index (19, 4124, 1)
delete_residue (19, "D", 82, "")
delete_residue_by_atom_index (19, 4124, 1)
delete_residue (19, "D", 83, "")
delete_residue_by_atom_index (19, 4123, 1)
clear_pending_delete_item ()
clear_pending_delete_item ()
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_delete_residue_mode ()
delete_residue (19, "D", 87, "")
delete_residue_by_atom_index (19, 4148, 1)
delete_residue (19, "D", 88, "")
delete_residue_by_atom_index (19, 4148, 1)
clear_pending_delete_item ()
clear_pending_delete_item ()
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_delete_residue_mode ()
delete_residue (19, "D", 85, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 4132, 1)
set_delete_residue_mode ()
delete_residue (19, "D", 86, "")
delete_residue_by_atom_index (19, 4132, 1)
delete_residue (19, "D", 84, "")
delete_residue_by_atom_index (19, 4124, 1)
delete_residue (19, "D", 68, "")
delete_residue_by_atom_index (19, 4107, 1)
delete_residue (19, "D", 69, "")
delete_residue_by_atom_index (19, 4101, 1)
apply_undo ()
apply_undo ()
clear_pending_delete_item ()
clear_pending_delete_item ()
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_delete_residue_mode ()
delete_residue (19, "D", 89, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 4124, 1)
set_delete_residue_mode ()
delete_residue (19, "D", 90, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 4127, 1)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_delete_residue_mode ()
delete_residue (19, "D", 164, "")
delete_residue_by_atom_index (19, 4682, 1)
delete_residue (19, "D", 169, "")
delete_residue_by_atom_index (19, 4715, 1)
delete_residue (19, "D", 165, "")
delete_residue_by_atom_index (19, 4684, 1)
delete_residue (19, "D", 166, "")
delete_residue_by_atom_index (19, 4681, 1)
delete_residue (19, "D", 49, "")
delete_residue_by_atom_index (19, 3961, 1)
delete_residue (19, "D", 168, "")
delete_residue_by_atom_index (19, 4677, 1)
delete_residue (19, "D", 170, "")
delete_residue_by_atom_index (19, 4677, 1)
delete_residue (19, "D", 167, "")
delete_residue_by_atom_index (19, 4673, 1)
clear_pending_delete_item ()
clear_pending_delete_item ()
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("VAL", 0)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("ASN", 0)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("LEU", 0)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("ASP", 0)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
apply_undo ()
apply_redo ()
apply_undo ()
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
apply_undo ()
apply_undo ()
set_go_to_atom_molecule (19)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("VAL", 0)
apply_undo ()
apply_undo ()
apply_undo ()
apply_undo ()
do_add_terminal_residue (1)
do_add_terminal_residue (0)
apply_undo ()
apply_undo ()
set_delete_residue_mode ()
delete_residue (19, "D", 167, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 4680, 1)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
apply_undo ()
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("VAL", 0)
;; # DIRECT SCHEME ((graphics-general-key-press-hook 65406))
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("GLU", 0)
set_go_to_atom_molecule (19)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
set_delete_residue_mode ()
delete_residue (19, "D", 165, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (19, 4680, 1)
do_add_terminal_residue (1)
do_add_terminal_residue (0)
setup_mutate_auto_fit (1)
setup_mutate_auto_fit (0)
do_mutatation ("GLU", 0)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
set_go_to_atom_molecule (19)
apply_undo ()
apply_undo ()
first_coords_imol ()
first_unsaved_coords_imol ()
filter_fileselection_filenames_state ()
