filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Evening Alfredo, Welcome to Coot version 0.8.9.2")
use_graphics_interface_state ()
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good evening Alfredo. Welcome to Coot 0.8.9.2")
set_display_lists_for_maps (0)
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
set_find_hydrogen_torsion (1)
use_graphics_interface_state ()
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_5/apo-ds1_refine_5.pdb", 1)
set_molecule_bonds_colour_map_rotation (0, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_5/apo-ds1_refine_5.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/pyrR/pyrR-apo-DS1/PhenixDS1-apo/Refine_5/apo-ds1_refine_5.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
;; # DIRECT SCHEME ((command-in-path-or-absolute? *probe-command*))
graphics_molecule_bond_type (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_delete_residue_mode ()
delete_residue (0, "A", 6, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (0, 27, 1)
set_delete_residue_mode ()
delete_residue (0, "A", 3, "")
delete_residue_by_atom_index (0, 5, 1)
delete_residue (0, "A", 4, "")
delete_residue_by_atom_index (0, 1, 1)
delete_residue (0, "A", 5, "")
delete_residue_by_atom_index (0, 1, 1)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
clear_pending_delete_item ()
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_delete_residue_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "A", 11, )
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
apply_undo ()
apply_undo ()
apply_undo ()
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
delete_residue_sidechain (0, "A", 76, )
set_delete_residue_mode ()
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (0, "A", 77, "")
delete_residue_by_atom_index (0, 560, 1)
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (0, "A", 78, "")
delete_residue_by_atom_index (0, 561, 1)
delete_residue (0, "A", 80, "")
delete_residue_by_atom_index (0, 569, 1)
delete_residue (0, "A", 79, "")
delete_residue_by_atom_index (0, 560, 1)
set_delete_residue_mode ()
clear_pending_delete_item ()
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (0, "A", 83, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (0, 582, 1)
set_delete_residue_mode ()
delete_residue (0, "A", 81, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (0, 565, 1)
set_delete_residue_mode ()
delete_residue (0, "A", 82, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (0, 560, 1)
set_delete_residue_mode ()
clear_pending_delete_item ()
clear_pending_delete_item ()
set_delete_residue_mode ()
delete_residue (0, "A", 92, "")
delete_residue_by_atom_index (0, 624, 1)
delete_residue (0, "A", 91, "")
delete_residue_by_atom_index (0, 619, 1)
delete_residue (0, "A", 90, "")
delete_residue_by_atom_index (0, 612, 1)
delete_residue (0, "A", 88, "")
delete_residue_by_atom_index (0, 593, 1)
delete_residue (0, "A", 65, "")
delete_residue_by_atom_index (0, 468, 1)
set_delete_residue_mode ()
delete_residue (0, "A", 89, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (0, 590, 1)
clear_pending_delete_item ()
clear_pending_delete_item ()
;; # DIRECT SCHEME ((graphics-general-key-press-hook 65406))
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_delete_residue_mode ()
delete_residue (0, "B", 3, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (0, 1249, 1)
set_delete_residue_mode ()
delete_residue (0, "B", 4, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (0, 1243, 1)
set_delete_residue_mode ()
set_delete_atom_mode ()
delete_atom (0, "B", 41, "", " NH2", "")
delete_atom (0, "B", 41, "", " CZ ", "")
delete_atom (0, "B", 41, "", " NE ", "")
delete_atom (0, "B", 41, "", " CD ", "")
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_atom_mode ()
delete_atom (0, "B", 41, "", " NH1", "")
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_sidechain_mode ()
first_coords_imol ()
first_unsaved_coords_imol ()
filter_fileselection_filenames_state ()
