(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Alfredo, Welcome to Coot version 0.8.9.2")
(use-graphics-interface-state)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon Alfredo. Welcome to Coot 0.8.9.2")
(set-display-lists-for-maps 0)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(set-find-hydrogen-torsion 1)
(use-graphics-interface-state)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/.comm/tmp.refine.pdb" 1)
(set-molecule-bonds-colour-map-rotation 0 140.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 1)
(close-molecule 2)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 3)
(close-molecule 4)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 5)
(close-molecule 6)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 7)
(close-molecule 8)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 9)
(close-molecule 10)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 0)
(close-molecule 11)
(close-molecule 12)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/apo_mpd-ds2_refine_3.pdb" 1)
(set-molecule-bonds-colour-map-rotation 13 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/apo_mpd-ds2_refine_3.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/phenix/DS2/Refine_3/apo_mpd-ds2_refine_3.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(command-in-path-or-absolute? *probe-command*)
