filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Evening Alfredo, Welcome to Coot version 0.8.9.2")
use_graphics_interface_state ()
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good evening Alfredo. Welcome to Coot 0.8.9.2")
set_display_lists_for_maps (0)
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
set_find_hydrogen_torsion (1)
use_graphics_interface_state ()
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine.pdb", 1)
set_molecule_bonds_colour_map_rotation (0, 140.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (1)
close_molecule (2)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (3)
close_molecule (4)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (5)
close_molecule (6)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (7)
close_molecule (8)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (9)
close_molecule (10)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (11)
close_molecule (12)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (13)
close_molecule (14)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (15)
close_molecule (16)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (17)
close_molecule (18)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (19)
close_molecule (20)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (21)
close_molecule (22)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (23)
close_molecule (24)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (25)
close_molecule (26)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (27)
close_molecule (28)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (0)
close_molecule (29)
close_molecule (30)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/refinement_pyrR-gmp-DS3_refine_2.pdb", 1)
set_molecule_bonds_colour_map_rotation (31, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/refinement_pyrR-gmp-DS3_refine_2.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/refinement_pyrR-gmp-DS3_refine_2.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
;; # DIRECT SCHEME ((command-in-path-or-absolute? *probe-command*))
