(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Evening Alfredo, Welcome to Coot version 0.8.9.2")
(use-graphics-interface-state)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good evening Alfredo. Welcome to Coot 0.8.9.2")
(set-display-lists-for-maps 0)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(set-find-hydrogen-torsion 1)
(use-graphics-interface-state)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine.pdb" 1)
(set-molecule-bonds-colour-map-rotation 0 140.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 1)
(close-molecule 2)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 3)
(close-molecule 4)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 5)
(close-molecule 6)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 7)
(close-molecule 8)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 9)
(close-molecule 10)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 11)
(close-molecule 12)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 13)
(close-molecule 14)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 15)
(close-molecule 16)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 17)
(close-molecule 18)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 19)
(close-molecule 20)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 21)
(close-molecule 22)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 23)
(close-molecule 24)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 25)
(close-molecule 26)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 27)
(close-molecule 28)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 0)
(close-molecule 29)
(close-molecule 30)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/refinement_pyrR-gmp-DS3_refine_2.pdb" 1)
(set-molecule-bonds-colour-map-rotation 31 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/refinement_pyrR-gmp-DS3_refine_2.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/Adriana/pyrR/pyrR-gmp-DS3/ref_phenix/Refine_2/refinement_pyrR-gmp-DS3_refine_2.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(command-in-path-or-absolute? *probe-command*)
