filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Evening Alfredo, Welcome to Coot version 0.8.9.2")
use_graphics_interface_state ()
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good evening Alfredo. Welcome to Coot 0.8.9.2")
set_display_lists_for_maps (0)
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
set_find_hydrogen_torsion (1)
use_graphics_interface_state ()
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_23/ValidationMac_refine_23.pdb", 1)
set_molecule_bonds_colour_map_rotation (0, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_23/ValidationMac_refine_23.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_23/ValidationMac_refine_23.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
do_rot_trans_setup (1)
rot_trans_reset_previous ()
rot_trans_reset_previous ()
apply_undo ()
apply_redo ()
do_rot_trans_setup (1)
rot_trans_reset_previous ()
rot_trans_reset_previous ()
do_rot_trans_setup (1)
apply_undo ()
rot_trans_reset_previous ()
rot_trans_reset_previous ()
do_rot_trans_setup (1)
rot_trans_reset_previous ()
rot_trans_reset_previous ()
apply_redo ()
apply_undo ()
do_rot_trans_setup (1)
rot_trans_reset_previous ()
rot_trans_reset_previous ()
do_rot_trans_setup (1)
rot_trans_reset_previous ()
rot_trans_reset_previous ()
do_rot_trans_setup (1)
rot_trans_reset_previous ()
rot_trans_reset_previous ()
first_coords_imol ()
first_unsaved_coords_imol ()
filter_fileselection_filenames_state ()
