(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Evening Alfredo, Welcome to Coot version 0.8.9.2")
(use-graphics-interface-state)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good evening Alfredo. Welcome to Coot 0.8.9.2")
(set-display-lists-for-maps 0)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(set-find-hydrogen-torsion 1)
(use-graphics-interface-state)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_23/ValidationMac_refine_23.pdb" 1)
(set-molecule-bonds-colour-map-rotation 0 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_23/ValidationMac_refine_23.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_23/ValidationMac_refine_23.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(do-rot-trans-setup 1)
(rot-trans-reset-previous)
(rot-trans-reset-previous)
(apply-undo)
(apply-redo)
(do-rot-trans-setup 1)
(rot-trans-reset-previous)
(rot-trans-reset-previous)
(do-rot-trans-setup 1)
(apply-undo)
(rot-trans-reset-previous)
(rot-trans-reset-previous)
(do-rot-trans-setup 1)
(rot-trans-reset-previous)
(rot-trans-reset-previous)
(apply-redo)
(apply-undo)
(do-rot-trans-setup 1)
(rot-trans-reset-previous)
(rot-trans-reset-previous)
(do-rot-trans-setup 1)
(rot-trans-reset-previous)
(rot-trans-reset-previous)
(do-rot-trans-setup 1)
(rot-trans-reset-previous)
(rot-trans-reset-previous)
(first-coords-imol)
(first-unsaved-coords-imol)
(filter-fileselection-filenames-state)
