(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Alfredo, Welcome to Coot version 0.8.9.2")
(use-graphics-interface-state)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon Alfredo. Welcome to Coot 0.8.9.2")
(set-display-lists-for-maps 0)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(set-find-hydrogen-torsion 1)
(use-graphics-interface-state)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine.pdb" 1)
(set-molecule-bonds-colour-map-rotation 0 140.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 1)
(close-molecule 2)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 3)
(close-molecule 4)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 5)
(close-molecule 6)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 7)
(close-molecule 8)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 9)
(close-molecule 10)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 11)
(close-molecule 12)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 13)
(close-molecule 14)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 15)
(close-molecule 16)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 0)
(close-molecule 17)
(close-molecule 18)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.pdb" 1)
(set-molecule-bonds-colour-map-rotation 19 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 19)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.pdb" 1)
(set-molecule-bonds-colour-map-rotation 22 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(command-in-path-or-absolute? *probe-command*)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(apply-undo)
(set-go-to-atom-molecule 22)
(apply-undo)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-delete-residue-mode)
(set-delete-residue-water-mode)
(delete-residue 22 "S" 124 "")
(clear-pending-delete-item)
(set-go-to-atom-molecule 22)
(set-delete-residue-water-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 22 "C" 39 )
(apply-undo)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 22 "A" 167 )
(set-go-to-atom-molecule 22)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(set-delete-residue-water-mode)
(delete-residue 22 "S" 158 "")
(clear-pending-delete-item)
(do-rot-trans-setup 1)
(rot-trans-reset-previous)
(rot-trans-reset-previous)
(apply-undo)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(apply-undo)
(apply-undo)
(apply-redo)
(apply-redo)
(apply-undo)
(apply-undo)
(apply-undo)
(apply-undo)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(apply-undo)
(apply-undo)
(apply-undo)
(apply-undo)
(apply-undo)
(apply-undo)
(set-go-to-atom-molecule 22)
(apply-undo)
(apply-undo)
(set-go-to-atom-molecule 22)
(apply-undo)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(apply-undo)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-clipping-front  0.02)
(set-clipping-back  0.04)
(set-go-to-atom-molecule 22)
(apply-undo)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(apply-undo)
(apply-undo)
(apply-undo)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(apply-undo)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(apply-redo)
(apply-undo)
(apply-undo)
(apply-redo)
(first-coords-imol)
(first-unsaved-coords-imol)
(filter-fileselection-filenames-state)
(first-coords-imol)
(first-unsaved-coords-imol)
(filter-fileselection-filenames-state)
(close-molecule 20)
(close-molecule 21)
(close-molecule 23)
(close-molecule 24)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine.pdb" 1)
(set-molecule-bonds-colour-map-rotation 25 140.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 26)
(close-molecule 27)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 28)
(close-molecule 29)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 30)
(close-molecule 31)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 32)
(close-molecule 33)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 34)
(close-molecule 35)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 36)
(close-molecule 37)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 38)
(close-molecule 39)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 40)
(close-molecule 41)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 25)
(close-molecule 42)
(close-molecule 43)
(close-molecule 22)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/ValidationMac_refine_3.pdb" 1)
(set-molecule-bonds-colour-map-rotation 44 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/ValidationMac_refine_3.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/ValidationMac_refine_3.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(setup-rotamers 1)
(setup-rotamers 0)
(set-delete-residue-water-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-atom-mode)
(delete-atom 44 "A" 53 "" " OE2" "")
(delete-atom 44 "A" 53 "" " OE1" "")
(delete-atom 44 "A" 53 "" " CD " "")
(delete-atom 44 "A" 53 "" " O  " "")
(setup-rotamers 1)
(delete-atom 44 "A" 53 "" " CB " "")
(apply-undo)
(apply-undo)
(apply-undo)
(delete-atom 44 "A" 55 "" " NH1" "")
(delete-atom 44 "A" 55 "" " CZ " "")
(delete-atom 44 "A" 55 "" " NH2" "")
(delete-atom 44 "A" 55 "" " NE " "")
(delete-atom 44 "A" 58 "" " NZ " "")
(delete-atom 44 "A" 58 "" " CE " "")
(delete-atom 44 "A" 58 "" " CD " "")
(delete-atom 44 "A" 73 "" " CA " "")
(apply-undo)
(apply-undo)
(clear-pending-delete-item)
(setup-rotamers 0)
(setup-rotamers 1)
(setup-rotamers 0)
(set-delete-residue-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 44 "A" 80 )
(setup-rotamers 1)
(setup-rotamers 0)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(set-delete-atom-mode)
(delete-atom 44 "A" 88 "" " CD1" "")
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-delete-residue-mode)
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-atom-mode)
(delete-atom 44 "B" 95 "" " NZ " "")
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-atom-mode)
(delete-atom 44 "B" 124 "" " NZ " "")
(delete-atom 44 "B" 124 "" " CE " "")
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-atom-mode)
(delete-atom 44 "B" 125 "" " OG " "")
(clear-pending-delete-item)
(setup-rotamers 1)
(setup-auto-fit-rotamer 1)
(setup-rotamers 0)
(setup-auto-fit-rotamer 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(apply-undo)
(apply-undo)
(apply-undo)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(set-delete-residue-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 44 "C" 30 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 44 "C" 53 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(set-delete-atom-mode)
(delete-atom 44 "C" 50 "" " NH2" "")
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-atom-mode)
(delete-atom 44 "C" 50 "" " NH1" "")
(delete-atom 44 "C" 50 "" " CZ " "")
(delete-atom 44 "C" 50 "" " NE " "")
(delete-atom 44 "C" 50 "" " CD " "")
(clear-pending-delete-item)
(set-add-alt-conf-split-type-number 1)
(set-undo-molecule 44)
(apply-undo)
(set-delete-residue-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 44 "C" 85 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(apply-undo)
(apply-undo)
(apply-undo)
(clear-pending-delete-item)
(delete-residue-sidechain 44 "C" 85 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 44 "C" 91 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(set-delete-atom-mode)
(delete-atom 44 "C" 124 "" " NZ " "")
(delete-atom 44 "C" 124 "" " CE " "")
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-atom-mode)
(delete-atom 44 "D" 58 "" " NZ " "")
(delete-atom 44 "D" 58 "" " CE " "")
(delete-atom 44 "D" 58 "" " CD " "")
(delete-atom 44 "D" 58 "" " CG " "")
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-residue-water-mode)
(delete-residue 44 "S" 153 "")
(clear-pending-delete-item)
(set-delete-residue-water-mode)
(set-delete-atom-mode)
(delete-atom 44 "D" 142 "" " CZ " "")
(delete-atom 44 "D" 142 "" " NH2" "")
(delete-atom 44 "D" 142 "" " NH1" "")
(delete-atom 44 "D" 142 "" " NE " "")
(clear-pending-delete-item)
(set-delete-residue-water-mode)
(set-delete-atom-mode)
(delete-atom 44 "D" 172 "" " CD1" "")
(clear-pending-delete-item)
(set-go-to-atom-molecule 44)
(set-go-to-atom-molecule 44)
(setup-rotamers 1)
(setup-rotamers 0)
(set-go-to-atom-molecule 44)
(set-delete-residue-water-mode)
(set-delete-atom-mode)
(delete-atom 44 "B" 39 "" " NH2" "")
(delete-atom 44 "B" 39 "" " CZ " "")
(delete-atom 44 "B" 39 "" " NH1" "")
(delete-atom 44 "B" 39 "" " NE " "")
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-go-to-atom-molecule 44)
(set-go-to-atom-molecule 44)
(setup-rotamers 1)
(setup-rotamers 0)
(set-go-to-atom-molecule 44)
(set-delete-residue-water-mode)
(set-delete-atom-mode)
(delete-atom 44 "D" 54 "" " NH1" "")
(delete-atom 44 "D" 54 "" " CZ " "")
(delete-atom 44 "D" 54 "" " NH2" "")
(delete-atom 44 "D" 54 "" " NE " "")
(delete-atom 44 "D" 54 "" " CD " "")
(delete-atom 44 "D" 54 "" " CG " "")
(clear-pending-delete-item)
(apply-undo)
(set-go-to-atom-molecule 44)
(set-go-to-atom-molecule 44)
(set-delete-residue-water-mode)
(set-delete-atom-mode)
(delete-atom 44 "A" 59 "" " NH2" "")
(delete-atom 44 "A" 59 "" " NH1" "")
(delete-atom 44 "A" 59 "" " CZ " "")
(delete-atom 44 "A" 59 "" " NE " "")
(clear-pending-delete-item)
(clear-pending-delete-item)
(set-go-to-atom-molecule 44)
(setup-rotamers 1)
(setup-rotamers 0)
(set-go-to-atom-molecule 44)
(setup-rotamers 1)
(setup-rotamers 0)
(set-delete-residue-water-mode)
(set-delete-atom-mode)
(delete-atom 44 "A" 74 "" " CD1" "")
(delete-atom 44 "A" 74 "" " CD2" "")
(clear-pending-delete-item)
(set-go-to-atom-molecule 44)
(setup-rotamers 1)
(setup-rotamers 0)
(setup-rotamers 1)
(setup-rotamers 0)
(setup-rotamers 1)
(setup-rotamers 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(set-go-to-atom-molecule 44)
(setup-rotamers 1)
(setup-rotamers 0)
(set-go-to-atom-molecule 44)
(set-go-to-atom-molecule 44)
(set-go-to-atom-molecule 44)
(first-coords-imol)
(first-unsaved-coords-imol)
(filter-fileselection-filenames-state)
(set-delete-residue-water-mode)
(delete-residue 44 "S" 16 "")
(delete-residue 44 "S" 19 "")
(delete-residue 44 "S" 45 "")
(delete-residue 44 "S" 61 "")
(delete-residue 44 "S" 63 "")
(delete-residue 44 "S" 84 "")
(delete-residue 44 "S" 85 "")
(delete-residue 44 "S" 149 "")
(delete-residue 44 "S" 136 "")
(delete-residue 44 "S" 100 "")
(delete-residue 44 "S" 108 "")
(delete-residue 44 "S" 113 "")
(delete-residue 44 "S" 114 "")
(delete-residue 44 "S" 123 "")
(delete-residue 44 "S" 124 "")
(delete-residue 44 "S" 127 "")
(delete-residue 44 "S" 128 "")
(delete-residue 44 "S" 134 "")
(delete-residue 44 "S" 147 "")
(delete-residue 44 "S" 151 "")
(delete-residue 44 "S" 156 "")
(delete-residue 44 "S" 164 "")
(first-coords-imol)
(first-unsaved-coords-imol)
(filter-fileselection-filenames-state)
(update-go-to-atom-window-on-other-molecule-chosen)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(clear-pending-delete-item)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(set-go-to-atom-molecule 22)
(first-coords-imol)
(first-unsaved-coords-imol)
(filter-fileselection-filenames-state)
