(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Evening Alfredo, Welcome to Coot version 0.8.9.2")
(use-graphics-interface-state)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good evening Alfredo. Welcome to Coot 0.8.9.2")
(set-display-lists-for-maps 0)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(set-find-hydrogen-torsion 1)
(use-graphics-interface-state)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.pdb" 1)
(set-molecule-bonds-colour-map-rotation 0 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(command-in-path-or-absolute? *probe-command*)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-delete-residue-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-delete-residue-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(apply-undo)
(set-go-to-atom-molecule 0)
(set-delete-residue-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "A" 167 )
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-go-to-atom-molecule 0)
(apply-undo)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-delete-residue-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "A" 75 )
(apply-undo)
(graphics-general-key-press-hook 122)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(apply-undo)
(set-go-to-atom-molecule 0)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "C" 38 )
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(apply-undo)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "A" 4 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(delete-residue-sidechain 0 "A" 9 )
(set-delete-atom-mode)
(delete-atom 0 "A" 19 "" " OG " "")
(set-delete-sidechain-mode)
(set-delete-residue-water-mode)
(delete-residue 0 "S" 160 "")
(set-delete-sidechain-mode)
(delete-residue-sidechain 0 "A" 30 )
(delete-residue-sidechain 0 "A" 95 )
(delete-residue-sidechain 0 "A" 53 )
(delete-residue-sidechain 0 "A" 93 )
(delete-residue-sidechain 0 "A" 125 )
(clear-pending-delete-item)
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "B" 2 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(set-delete-atom-mode)
(delete-atom 0 "B" 19 "" " OG " "")
(clear-pending-delete-item)
(apply-undo)
(set-delete-residue-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "B" 69 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "B" 86 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "B" 122 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(set-delete-atom-mode)
(delete-atom 0 "B" 124 "" " NZ " "")
(delete-atom 0 "B" 124 "" " CE " "")
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-atom-mode)
(delete-atom 0 "B" 125 "" " OG " "")
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "C" 4 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "C" 25 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "C" 50 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "C" 53 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "C" 86 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "C" 93 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "C" 91 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "C" 162 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "D" 1 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "D" 93 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(clear-pending-delete-item)
(delete-residue-sidechain 0 "D" 142 )
(set-delete-sidechain-mode)
(set-delete-sidechain-mode)
(set-delete-residue-water-mode)
(delete-residue 0 "S" 111 "")
(clear-pending-delete-item)
(set-delete-residue-water-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-delete-residue-mode)
(set-delete-residue-water-mode)
(delete-residue 0 "S" 143 "")
(clear-pending-delete-item)
(set-delete-residue-water-mode)
(delete-residue 0 "S" 144 "")
(clear-pending-delete-item)
(set-delete-residue-water-mode)
(delete-residue 0 "S" 150 "")
(clear-pending-delete-item)
(set-delete-residue-water-mode)
(delete-residue 0 "S" 164 "")
(clear-pending-delete-item)
(set-delete-residue-water-mode)
(delete-residue 0 "S" 20 "")
(delete-residue 0 "S" 171 "")
(delete-residue 0 "S" 63 "")
(delete-residue 0 "S" 77 "")
(delete-residue 0 "S" 79 "")
(delete-residue 0 "S" 87 "")
(delete-residue 0 "S" 166 "")
(delete-residue 0 "S" 109 "")
(delete-residue 0 "S" 92 "")
(delete-residue 0 "S" 93 "")
(delete-residue 0 "S" 106 "")
(delete-residue 0 "S" 120 "")
(delete-residue 0 "S" 122 "")
(delete-residue 0 "S" 127 "")
(delete-residue 0 "S" 128 "")
(delete-residue 0 "S" 132 "")
(delete-residue 0 "S" 133 "")
(delete-residue 0 "S" 134 "")
(delete-residue 0 "S" 148 "")
(delete-residue 0 "S" 156 "")
(delete-residue 0 "S" 158 "")
(delete-residue 0 "S" 165 "")
(delete-residue 0 "S" 168 "")
(delete-residue 0 "S" 170 "")
(delete-residue 0 "S" 175 "")
(delete-residue 0 "S" 176 "")
(delete-atom 0 "S" 177 "" " O  " "")
(clear-pending-delete-item)
(place-atom-at-pointer)
(place-typed-atom-at-pointer "Water")
(place-atom-at-pointer)
(place-typed-atom-at-pointer "Water")
(set-clipping-front  0.02)
(set-clipping-back  0.04)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(setup-rotamers 1)
(setup-rotamers 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(set-go-to-atom-molecule 0)
(apply-undo)
(set-go-to-atom-molecule 0)
(apply-undo)
(apply-undo)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-delete-residue-water-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-go-to-atom-molecule 0)
(set-delete-residue-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-delete-residue-mode)
(delete-residue 0 "C" 54 "")
(clear-pending-delete-item)
(delete-residue-by-atom-index 0 2939 1)
(apply-undo)
(set-delete-residue-mode)
(set-delete-sidechain-range-mode)
(clear-pending-delete-item)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(setup-rotamers 1)
(setup-rotamers 0)
(setup-torsion-general 1)
(set-delete-residue-mode)
(set-delete-atom-mode)
(delete-atom 0 "A" 59 "" " NH1" "")
(delete-atom 0 "A" 59 "" " CZ " "")
(delete-atom 0 "A" 59 "" " NH2" "")
(delete-atom 0 "A" 59 "" " NE " "")
(clear-pending-delete-item)
(setup-torsion-general 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(apply-undo)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-molecule 0)
(apply-undo)
(apply-undo)
(apply-undo)
(apply-undo)
(graphics-general-key-press-hook 65406)
(first-coords-imol)
(first-unsaved-coords-imol)
(filter-fileselection-filenames-state)
(close-molecule 1)
(close-molecule 2)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine.pdb" 1)
(set-molecule-bonds-colour-map-rotation 3 140.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 4)
(close-molecule 5)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 6)
(close-molecule 7)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 8)
(close-molecule 9)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 10)
(close-molecule 11)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 12)
(close-molecule 13)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 14)
(close-molecule 15)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 16)
(close-molecule 17)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 18)
(close-molecule 19)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 3)
(close-molecule 20)
(close-molecule 21)
(close-molecule 0)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/ValidationMac_refine_26.pdb" 1)
(set-molecule-bonds-colour-map-rotation 22 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/ValidationMac_refine_26.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/ValidationMac_refine_26.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 23)
(close-molecule 24)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/.comm/tmp.refine.pdb" 1)
(set-molecule-bonds-colour-map-rotation 25 140.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 26)
(close-molecule 27)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
(close-molecule 25)
(close-molecule 28)
(close-molecule 29)
(close-molecule 22)
(handle-read-draw-molecule-with-recentre "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/validacionMac_ds2_refine_3.pdb" 1)
(set-molecule-bonds-colour-map-rotation 30 30.00)
(set-colour-map-rotation-for-map  0.00)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/validacionMac_ds2_refine_3.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/validacionMac_ds2_refine_3.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map  0.00)
