filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Evening Alfredo, Welcome to Coot version 0.8.9.2")
use_graphics_interface_state ()
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good evening Alfredo. Welcome to Coot 0.8.9.2")
set_display_lists_for_maps (0)
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
set_find_hydrogen_torsion (1)
use_graphics_interface_state ()
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.pdb", 1)
set_molecule_bonds_colour_map_rotation (0, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
;; # DIRECT SCHEME ((command-in-path-or-absolute? *probe-command*))
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_delete_residue_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_delete_residue_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
apply_undo ()
set_go_to_atom_molecule (0)
set_delete_residue_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "A", 167, )
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_go_to_atom_molecule (0)
apply_undo ()
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_delete_residue_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "A", 75, )
apply_undo ()
;; # DIRECT SCHEME ((graphics-general-key-press-hook 122))
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
apply_undo ()
set_go_to_atom_molecule (0)
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "C", 38, )
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
apply_undo ()
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "A", 4, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
delete_residue_sidechain (0, "A", 9, )
set_delete_atom_mode ()
delete_atom (0, "A", 19, "", " OG ", "")
set_delete_sidechain_mode ()
set_delete_residue_water_mode ()
delete_residue (0, "S", 160, "")
set_delete_sidechain_mode ()
delete_residue_sidechain (0, "A", 30, )
delete_residue_sidechain (0, "A", 95, )
delete_residue_sidechain (0, "A", 53, )
delete_residue_sidechain (0, "A", 93, )
delete_residue_sidechain (0, "A", 125, )
clear_pending_delete_item ()
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "B", 2, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
set_delete_atom_mode ()
delete_atom (0, "B", 19, "", " OG ", "")
clear_pending_delete_item ()
apply_undo ()
set_delete_residue_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "B", 69, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "B", 86, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "B", 122, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
set_delete_atom_mode ()
delete_atom (0, "B", 124, "", " NZ ", "")
delete_atom (0, "B", 124, "", " CE ", "")
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_atom_mode ()
delete_atom (0, "B", 125, "", " OG ", "")
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "C", 4, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "C", 25, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "C", 50, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "C", 53, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "C", 86, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "C", 93, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "C", 91, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "C", 162, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "D", 1, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "D", 93, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (0, "D", 142, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
set_delete_residue_water_mode ()
delete_residue (0, "S", 111, "")
clear_pending_delete_item ()
set_delete_residue_water_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_residue_water_mode ()
delete_residue (0, "S", 143, "")
clear_pending_delete_item ()
set_delete_residue_water_mode ()
delete_residue (0, "S", 144, "")
clear_pending_delete_item ()
set_delete_residue_water_mode ()
delete_residue (0, "S", 150, "")
clear_pending_delete_item ()
set_delete_residue_water_mode ()
delete_residue (0, "S", 164, "")
clear_pending_delete_item ()
set_delete_residue_water_mode ()
delete_residue (0, "S", 20, "")
delete_residue (0, "S", 171, "")
delete_residue (0, "S", 63, "")
delete_residue (0, "S", 77, "")
delete_residue (0, "S", 79, "")
delete_residue (0, "S", 87, "")
delete_residue (0, "S", 166, "")
delete_residue (0, "S", 109, "")
delete_residue (0, "S", 92, "")
delete_residue (0, "S", 93, "")
delete_residue (0, "S", 106, "")
delete_residue (0, "S", 120, "")
delete_residue (0, "S", 122, "")
delete_residue (0, "S", 127, "")
delete_residue (0, "S", 128, "")
delete_residue (0, "S", 132, "")
delete_residue (0, "S", 133, "")
delete_residue (0, "S", 134, "")
delete_residue (0, "S", 148, "")
delete_residue (0, "S", 156, "")
delete_residue (0, "S", 158, "")
delete_residue (0, "S", 165, "")
delete_residue (0, "S", 168, "")
delete_residue (0, "S", 170, "")
delete_residue (0, "S", 175, "")
delete_residue (0, "S", 176, "")
delete_atom (0, "S", 177, "", " O  ", "")
clear_pending_delete_item ()
place_atom_at_pointer ()
place_typed_atom_at_pointer ("Water")
place_atom_at_pointer ()
place_typed_atom_at_pointer ("Water")
set_clipping_front ( 0.02)
set_clipping_back ( 0.04)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
setup_rotamers (1)
setup_rotamers (0)
setup_auto_fit_rotamer (1)
setup_auto_fit_rotamer (0)
set_go_to_atom_molecule (0)
apply_undo ()
set_go_to_atom_molecule (0)
apply_undo ()
apply_undo ()
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_delete_residue_water_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_go_to_atom_molecule (0)
set_delete_residue_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_delete_residue_mode ()
delete_residue (0, "C", 54, "")
clear_pending_delete_item ()
delete_residue_by_atom_index (0, 2939, 1)
apply_undo ()
set_delete_residue_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
setup_rotamers (1)
setup_rotamers (0)
setup_torsion_general (1)
set_delete_residue_mode ()
set_delete_atom_mode ()
delete_atom (0, "A", 59, "", " NH1", "")
delete_atom (0, "A", 59, "", " CZ ", "")
delete_atom (0, "A", 59, "", " NH2", "")
delete_atom (0, "A", 59, "", " NE ", "")
clear_pending_delete_item ()
setup_torsion_general (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
setup_auto_fit_rotamer (1)
setup_auto_fit_rotamer (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
setup_auto_fit_rotamer (1)
setup_auto_fit_rotamer (0)
apply_undo ()
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
set_go_to_atom_molecule (0)
apply_undo ()
apply_undo ()
apply_undo ()
apply_undo ()
;; # DIRECT SCHEME ((graphics-general-key-press-hook 65406))
first_coords_imol ()
first_unsaved_coords_imol ()
filter_fileselection_filenames_state ()
close_molecule (1)
close_molecule (2)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine.pdb", 1)
set_molecule_bonds_colour_map_rotation (3, 140.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (4)
close_molecule (5)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (6)
close_molecule (7)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (8)
close_molecule (9)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (10)
close_molecule (11)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (12)
close_molecule (13)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (14)
close_molecule (15)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (16)
close_molecule (17)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (18)
close_molecule (19)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (3)
close_molecule (20)
close_molecule (21)
close_molecule (0)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/ValidationMac_refine_26.pdb", 1)
set_molecule_bonds_colour_map_rotation (22, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/ValidationMac_refine_26.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_26/ValidationMac_refine_26.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (23)
close_molecule (24)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/.comm/tmp.refine.pdb", 1)
set_molecule_bonds_colour_map_rotation (25, 140.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (26)
close_molecule (27)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (25)
close_molecule (28)
close_molecule (29)
close_molecule (22)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/validacionMac_ds2_refine_3.pdb", 1)
set_molecule_bonds_colour_map_rotation (30, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/validacionMac_ds2_refine_3.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac2/Refine_3/validacionMac_ds2_refine_3.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
