filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Alfredo, Welcome to Coot version 0.8.9.2")
use_graphics_interface_state ()
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good afternoon Alfredo. Welcome to Coot 0.8.9.2")
set_display_lists_for_maps (0)
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
set_find_hydrogen_torsion (1)
use_graphics_interface_state ()
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine.pdb", 1)
set_molecule_bonds_colour_map_rotation (0, 140.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (1)
close_molecule (2)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (3)
close_molecule (4)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (5)
close_molecule (6)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (7)
close_molecule (8)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (9)
close_molecule (10)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (11)
close_molecule (12)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (13)
close_molecule (14)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (15)
close_molecule (16)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (0)
close_molecule (17)
close_molecule (18)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.pdb", 1)
set_molecule_bonds_colour_map_rotation (19, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (19)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.pdb", 1)
set_molecule_bonds_colour_map_rotation (22, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_1/ValidationMac_refine_1.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
;; # DIRECT SCHEME ((command-in-path-or-absolute? *probe-command*))
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
apply_undo ()
set_go_to_atom_molecule (22)
apply_undo ()
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_delete_residue_mode ()
set_delete_residue_water_mode ()
delete_residue (22, "S", 124, "")
clear_pending_delete_item ()
set_go_to_atom_molecule (22)
set_delete_residue_water_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (22, "C", 39, )
apply_undo ()
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (22, "A", 167, )
set_go_to_atom_molecule (22)
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
set_delete_residue_water_mode ()
delete_residue (22, "S", 158, "")
clear_pending_delete_item ()
do_rot_trans_setup (1)
rot_trans_reset_previous ()
rot_trans_reset_previous ()
apply_undo ()
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
apply_undo ()
apply_undo ()
apply_redo ()
apply_redo ()
apply_undo ()
apply_undo ()
apply_undo ()
apply_undo ()
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
apply_undo ()
apply_undo ()
apply_undo ()
apply_undo ()
apply_undo ()
apply_undo ()
set_go_to_atom_molecule (22)
apply_undo ()
apply_undo ()
set_go_to_atom_molecule (22)
apply_undo ()
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
apply_undo ()
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_clipping_front ( 0.02)
set_clipping_back ( 0.04)
set_go_to_atom_molecule (22)
apply_undo ()
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
apply_undo ()
apply_undo ()
apply_undo ()
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
apply_undo ()
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
apply_redo ()
apply_undo ()
apply_undo ()
apply_redo ()
first_coords_imol ()
first_unsaved_coords_imol ()
filter_fileselection_filenames_state ()
first_coords_imol ()
first_unsaved_coords_imol ()
filter_fileselection_filenames_state ()
close_molecule (20)
close_molecule (21)
close_molecule (23)
close_molecule (24)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine.pdb", 1)
set_molecule_bonds_colour_map_rotation (25, 140.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (26)
close_molecule (27)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (28)
close_molecule (29)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (30)
close_molecule (31)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (32)
close_molecule (33)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (34)
close_molecule (35)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (36)
close_molecule (37)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (38)
close_molecule (39)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (40)
close_molecule (41)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
close_molecule (25)
close_molecule (42)
close_molecule (43)
close_molecule (22)
handle_read_draw_molecule_with_recentre ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/ValidationMac_refine_3.pdb", 1)
set_molecule_bonds_colour_map_rotation (44, 30.00)
set_colour_map_rotation_for_map ( 0.00)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/ValidationMac_refine_3.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/Users/alfredo/Documents/GitHub/Xtalab_estruturas_pyrR/Validation/ValidationMac/Refine_3/ValidationMac_refine_3.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map ( 0.00)
setup_rotamers (1)
setup_rotamers (0)
set_delete_residue_water_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_atom_mode ()
delete_atom (44, "A", 53, "", " OE2", "")
delete_atom (44, "A", 53, "", " OE1", "")
delete_atom (44, "A", 53, "", " CD ", "")
delete_atom (44, "A", 53, "", " O  ", "")
setup_rotamers (1)
delete_atom (44, "A", 53, "", " CB ", "")
apply_undo ()
apply_undo ()
apply_undo ()
delete_atom (44, "A", 55, "", " NH1", "")
delete_atom (44, "A", 55, "", " CZ ", "")
delete_atom (44, "A", 55, "", " NH2", "")
delete_atom (44, "A", 55, "", " NE ", "")
delete_atom (44, "A", 58, "", " NZ ", "")
delete_atom (44, "A", 58, "", " CE ", "")
delete_atom (44, "A", 58, "", " CD ", "")
delete_atom (44, "A", 73, "", " CA ", "")
apply_undo ()
apply_undo ()
clear_pending_delete_item ()
setup_rotamers (0)
setup_rotamers (1)
setup_rotamers (0)
set_delete_residue_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (44, "A", 80, )
setup_rotamers (1)
setup_rotamers (0)
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
set_delete_atom_mode ()
delete_atom (44, "A", 88, "", " CD1", "")
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_delete_residue_mode ()
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_atom_mode ()
delete_atom (44, "B", 95, "", " NZ ", "")
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_atom_mode ()
delete_atom (44, "B", 124, "", " NZ ", "")
delete_atom (44, "B", 124, "", " CE ", "")
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_atom_mode ()
delete_atom (44, "B", 125, "", " OG ", "")
clear_pending_delete_item ()
setup_rotamers (1)
setup_auto_fit_rotamer (1)
setup_rotamers (0)
setup_auto_fit_rotamer (0)
setup_auto_fit_rotamer (1)
setup_auto_fit_rotamer (0)
apply_undo ()
apply_undo ()
apply_undo ()
setup_auto_fit_rotamer (1)
setup_auto_fit_rotamer (0)
set_delete_residue_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (44, "C", 30, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (44, "C", 53, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
set_delete_atom_mode ()
delete_atom (44, "C", 50, "", " NH2", "")
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_atom_mode ()
delete_atom (44, "C", 50, "", " NH1", "")
delete_atom (44, "C", 50, "", " CZ ", "")
delete_atom (44, "C", 50, "", " NE ", "")
delete_atom (44, "C", 50, "", " CD ", "")
clear_pending_delete_item ()
set_add_alt_conf_split_type_number (1)
set_undo_molecule (44)
apply_undo ()
set_delete_residue_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (44, "C", 85, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
apply_undo ()
apply_undo ()
apply_undo ()
clear_pending_delete_item ()
delete_residue_sidechain (44, "C", 85, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
clear_pending_delete_item ()
delete_residue_sidechain (44, "C", 91, )
set_delete_sidechain_mode ()
set_delete_sidechain_mode ()
set_delete_atom_mode ()
delete_atom (44, "C", 124, "", " NZ ", "")
delete_atom (44, "C", 124, "", " CE ", "")
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_sidechain_range_mode ()
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_atom_mode ()
delete_atom (44, "D", 58, "", " NZ ", "")
delete_atom (44, "D", 58, "", " CE ", "")
delete_atom (44, "D", 58, "", " CD ", "")
delete_atom (44, "D", 58, "", " CG ", "")
clear_pending_delete_item ()
set_delete_residue_mode ()
set_delete_residue_water_mode ()
delete_residue (44, "S", 153, "")
clear_pending_delete_item ()
set_delete_residue_water_mode ()
set_delete_atom_mode ()
delete_atom (44, "D", 142, "", " CZ ", "")
delete_atom (44, "D", 142, "", " NH2", "")
delete_atom (44, "D", 142, "", " NH1", "")
delete_atom (44, "D", 142, "", " NE ", "")
clear_pending_delete_item ()
set_delete_residue_water_mode ()
set_delete_atom_mode ()
delete_atom (44, "D", 172, "", " CD1", "")
clear_pending_delete_item ()
set_go_to_atom_molecule (44)
set_go_to_atom_molecule (44)
setup_rotamers (1)
setup_rotamers (0)
set_go_to_atom_molecule (44)
set_delete_residue_water_mode ()
set_delete_atom_mode ()
delete_atom (44, "B", 39, "", " NH2", "")
delete_atom (44, "B", 39, "", " CZ ", "")
delete_atom (44, "B", 39, "", " NH1", "")
delete_atom (44, "B", 39, "", " NE ", "")
clear_pending_delete_item ()
clear_pending_delete_item ()
set_go_to_atom_molecule (44)
set_go_to_atom_molecule (44)
setup_rotamers (1)
setup_rotamers (0)
set_go_to_atom_molecule (44)
set_delete_residue_water_mode ()
set_delete_atom_mode ()
delete_atom (44, "D", 54, "", " NH1", "")
delete_atom (44, "D", 54, "", " CZ ", "")
delete_atom (44, "D", 54, "", " NH2", "")
delete_atom (44, "D", 54, "", " NE ", "")
delete_atom (44, "D", 54, "", " CD ", "")
delete_atom (44, "D", 54, "", " CG ", "")
clear_pending_delete_item ()
apply_undo ()
set_go_to_atom_molecule (44)
set_go_to_atom_molecule (44)
set_delete_residue_water_mode ()
set_delete_atom_mode ()
delete_atom (44, "A", 59, "", " NH2", "")
delete_atom (44, "A", 59, "", " NH1", "")
delete_atom (44, "A", 59, "", " CZ ", "")
delete_atom (44, "A", 59, "", " NE ", "")
clear_pending_delete_item ()
clear_pending_delete_item ()
set_go_to_atom_molecule (44)
setup_rotamers (1)
setup_rotamers (0)
set_go_to_atom_molecule (44)
setup_rotamers (1)
setup_rotamers (0)
set_delete_residue_water_mode ()
set_delete_atom_mode ()
delete_atom (44, "A", 74, "", " CD1", "")
delete_atom (44, "A", 74, "", " CD2", "")
clear_pending_delete_item ()
set_go_to_atom_molecule (44)
setup_rotamers (1)
setup_rotamers (0)
setup_rotamers (1)
setup_rotamers (0)
setup_rotamers (1)
setup_rotamers (0)
setup_auto_fit_rotamer (1)
setup_auto_fit_rotamer (0)
set_go_to_atom_molecule (44)
setup_rotamers (1)
setup_rotamers (0)
set_go_to_atom_molecule (44)
set_go_to_atom_molecule (44)
set_go_to_atom_molecule (44)
first_coords_imol ()
first_unsaved_coords_imol ()
filter_fileselection_filenames_state ()
set_delete_residue_water_mode ()
delete_residue (44, "S", 16, "")
delete_residue (44, "S", 19, "")
delete_residue (44, "S", 45, "")
delete_residue (44, "S", 61, "")
delete_residue (44, "S", 63, "")
delete_residue (44, "S", 84, "")
delete_residue (44, "S", 85, "")
delete_residue (44, "S", 149, "")
delete_residue (44, "S", 136, "")
delete_residue (44, "S", 100, "")
delete_residue (44, "S", 108, "")
delete_residue (44, "S", 113, "")
delete_residue (44, "S", 114, "")
delete_residue (44, "S", 123, "")
delete_residue (44, "S", 124, "")
delete_residue (44, "S", 127, "")
delete_residue (44, "S", 128, "")
delete_residue (44, "S", 134, "")
delete_residue (44, "S", 147, "")
delete_residue (44, "S", 151, "")
delete_residue (44, "S", 156, "")
delete_residue (44, "S", 164, "")
first_coords_imol ()
first_unsaved_coords_imol ()
filter_fileselection_filenames_state ()
update_go_to_atom_window_on_other_molecule_chosen ()
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
clear_pending_delete_item ()
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
set_go_to_atom_molecule (22)
first_coords_imol ()
first_unsaved_coords_imol ()
filter_fileselection_filenames_state ()
